package persistence;

import com.fasterxml.jackson.core.type.TypeReference;
import core.Post;
import core.User;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Value;
import persistence.json.JsonRepository;

// This JavaDoc comment was generated by Github Copilot
/**
 * Repository implementation for Post entities backed by a JSON file.
 *
 * @deprecated This repository is deprecated because the project now uses SQLite
 *             with Hibernate for persistence instead of JSON files. Use
 *             {@link OrmPostRepository} instead.
 */
@Deprecated
public class JsonPostRepository implements PostRepository {
  private final JsonRepository<Post> jsonRepository;
  private List<Post> posts;

  // This JavaDoc comment was generated by Github Copilot
  /**
   * Constructs a JsonPostRepository using the given data directory path.
   *
   * @param dataDirPath the path to the directory where posts.json is stored
   */
  public JsonPostRepository(@Value("${app.data.directory}") String dataDirPath) {
    Path dataDir = Paths.get(dataDirPath);
    try {
      Files.createDirectories(dataDir);
    } catch (IOException e) {
      e.printStackTrace();
    }

    this.jsonRepository = new JsonRepository<>(dataDir.resolve("posts.json"),
        new TypeReference<List<Post>>() {
        });

    // FIXME: Don't load every post into memory :)
    this.loadPosts();
  }

  private void loadPosts() {
    try {
      this.posts = this.jsonRepository.load();
    } catch (IOException e) {
      this.posts = new ArrayList<>();
    }
  }

  // This JavaDoc comment was generated by Github Copilot
  /**
   * Saves the current list of posts to the JSON file.
   */
  public void savePosts() {
    try {
      this.jsonRepository.save(this.posts);
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  // This JavaDoc comment was generated by Github Copilot
  /**
   * Adds a new post to the repository and saves it.
   *
   * @param newPost the post to add
   */
  public void addPost(Post newPost) {
    this.posts.add(newPost);
    this.savePosts();
  }

  @Override
  public Optional<Post> findById(Long id, boolean withRelations) {
    throw new UnsupportedOperationException("Method 'findById' using the 'withRealtions' boolean "
        + "is unimplemented in JsonPostRepository");
  }

  @Override
  public Optional<Post> findById(Long id) {
    return this.posts.stream().filter(post -> post.getId().equals(id)).findFirst();
  }

  @Override
  public List<Post> findAll() {
    return new ArrayList<>(this.posts);
  }

  @Override
  public List<Post> findAll(boolean withRelations) {
    throw new UnsupportedOperationException("Method 'findAll' using the 'withRealtions' boolean "
        + "is unimplemented in JsonPostRepository");
  }

  @Override
  public Post save(Post post) {
    this.addPost(post);
    return post;
  }

  @Override
  public Post update(Post post) {
    return save(post);
  }

  @Override
  public void deleteById(Long id) {
    this.posts.removeIf(post -> post.getId().equals(id));
  }

  @Override
  public boolean existsById(Long id) {
    return this.findById(id).isPresent();
  }

  @Override
  public Post likePost(Post post, User user) {
    throw new UnsupportedOperationException("Unimplemented method 'likePost'");
  }

  @Override
  public Post updateRetweetCount(Post post) {
    throw new UnsupportedOperationException("Unimplemented method 'toggleRetweet'");
  }

  @Override
  public List<Post> findPostsByUser(User user) {
    throw new UnsupportedOperationException("Unimplemented method 'findPostsByUser'");
  }
}
