package persistence;

import com.fasterxml.jackson.core.type.TypeReference;
import core.User;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;
import org.springframework.beans.factory.annotation.Value;
import persistence.json.JsonRepository;

// This JavaDoc comment was generated by Github Copilot
/**
 * Repository implementation for User entities backed by a JSON file.
 *
 * @deprecated This repository is deprecated because the project now uses SQLite
 *             with Hibernate for persistence instead of JSON files. Use
 *             {@link OrmUserRepository} instead.
 */
@Deprecated
public class JsonUserRepository implements UserRepository {
  private AtomicLong nextId = new AtomicLong(0);
  private final JsonRepository<User> jsonRepository;
  private List<User> users;

  // This JavaDoc comment was generated by Github Copilot
  /**
   * Constructs a JsonUserRepository using the given data directory path.
   *
   * @param dataDirPath the path to the directory where users.json is stored
   */
  public JsonUserRepository(@Value("${app.data.directory}") String dataDirPath) {
    Path dataDir = Paths.get(dataDirPath);
    try {
      Files.createDirectories(dataDir);
    } catch (IOException e) {
      e.printStackTrace();
    }

    this.jsonRepository = new JsonRepository<>(dataDir.resolve("users.json"), new TypeReference<List<User>>() {
    });

    // FIXME: Don't load every user into memory :)
    this.loadUsers();
    Long nextId = this.users.stream().map(User::getId).max(Comparator.naturalOrder()).orElse(0L)
        + 1;
    this.nextId.set(nextId);
  }

  // This JavaDoc comment was generated by Github Copilot
  /**
   * Loads users from the JSON file into memory. If loading fails, initializes an
   * empty list.
   */
  private void loadUsers() {
    try {
      this.users = this.jsonRepository.load();
    } catch (IOException e) {
      this.users = new ArrayList<>();
    }
  }

  // This JavaDoc comment was generated by Github Copilot
  /**
   * Saves the current list of users to the JSON file.
   */
  public void saveUsers() {
    try {
      this.jsonRepository.save(this.users);
    } catch (IOException e) {
      System.err.println(e);
    }
  }

  // This JavaDoc comment was generated by Github Copilot
  /**
   * Adds a new user to the repository and saves it.
   *
   * @param user the user to add
   */
  public void addUser(User user) {
    this.users.add(user);
    this.saveUsers();
  }

  @Override
  public Optional<User> findById(Long id) {
    return this.users.stream().filter(user -> user.getId().equals(id)).findFirst();
  }

  @Override
  public List<User> findAll() {
    return new ArrayList<>(this.users);
  }

  @Override
  public User save(User user) {
    if (user.getId() == null) {
      user.setId(nextId.getAndIncrement());
    }

    this.addUser(user);
    return user;
  }

  @Override
  public User update(User user) {
    return save(user);
  }

  @Override
  public void deleteById(Long id) {
    this.users.removeIf(user -> user.getId().equals(id));
  }

  @Override
  public boolean existsById(Long id) {
    return this.users.stream().anyMatch(user -> user.getId().equals(id));
  }

  @Override
  public Optional<User> findByUsername(String username) {
    return this.users.stream().filter(user -> user.getUsername().equals(username)).findFirst();
  }
}
