package persistence;

import java.util.HashSet;
import java.util.List;
import java.util.Optional;

import core.Post;
import core.User;
import persistence.hibernate.HibernateRepository;

// This JavaDoc comment was generated by Github Copilot
/**
 * The OrmPostRepository class provides an implementation of the PostRepository
 * interface using Hibernate for database operations.
 */
public class OrmPostRepository extends HibernateRepository implements PostRepository {
  @Override
  public void deleteById(Long id) {
    sessionFactory.inTransaction(session -> {
      Post post = session.find(Post.class, id);
      if (post != null) {
        session.remove(post);
      }
    });
  }

  @Override
  public boolean existsById(Long id) {
    return sessionFactory.fromTransaction(session -> {
      return session.find(Post.class, id) != null;
    });
  }

  @Override
  public List<Post> findAll() {
    return this.findAll(false);
  }

  @Override
  public List<Post> findAll(boolean withRelations) {
    if (withRelations) {
      return sessionFactory.fromTransaction(session -> {
        List<Post> posts = session
            .createSelectionQuery("FROM Post p LEFT JOIN FETCH p.likedByUsers", Post.class)
            .getResultList();
        return posts;
      });
    }

    return sessionFactory.fromTransaction(session -> {
      List<Post> posts = session.createQuery("SELECT p FROM Post p", Post.class).getResultList();
      return posts;
    });
  }

  @Override
  public Optional<Post> findById(Long id) {
    return this.findById(id, false);
  }

  @Override
  public Optional<Post> findById(Long id, boolean withRelations) {
    if (withRelations) {
      return sessionFactory.fromTransaction(session -> {
        Post post = session
            .createQuery("SELECT p FROM Post p LEFT JOIN FETCH p.likedByUsers WHERE p.id = :id",
                Post.class)
            .setParameter("id", id).getSingleResult();
        return Optional.ofNullable(post);
      });
    }

    return sessionFactory.fromTransaction(session -> {
      Post post = session.find(Post.class, id);
      return Optional.ofNullable(post);
    });
  }

  @Override
  public Post save(Post post) {
    sessionFactory.inTransaction(session -> {
      session.persist(post);
    });
    return post;
  }

  @Override
  public Post update(Post post) {
    return sessionFactory.fromTransaction(session -> {
      Post managedPost = session.find(Post.class, post.getId());
      if (managedPost != null) {
        managedPost.setContent(post.getContent());

        // Sync liked users properly
        managedPost.setLikedByUsers(post.getLikedByUsers());
        managedPost.setLikes(post.getLikes());
      }
      return managedPost;
    });
  }

  @Override
  public Post likePost(Post post, User user) {
    return sessionFactory.fromTransaction(session -> {
      HashSet<User> likedByUsers = new HashSet<>(post.getLikedByUsers());
      if (likedByUsers.contains(user)) {
        likedByUsers.remove(user);
      } else {
        likedByUsers.add(user);
      }
      post.setLikedByUsers(likedByUsers);
      post.setLikes(likedByUsers.size());
      return session.merge(post);
    });
  }

  @Override
  public List<Post> findPostsByUser(User user) {
    return sessionFactory.fromTransaction(session -> {
      List<Post> posts = session
          .createSelectionQuery("FROM Post p LEFT JOIN FETCH p.likedByUsers WHERE p.author = :user",
              Post.class)
          .setParameter("user", user).getResultList();
      return posts;
    });
  }

  @Override
  public int getPostCount(User user) {
    List<Post> posts = findPostsByUser(user);
    return posts.size();
  }

  @Override
  public int getLikesCount(User user) {
    List<Post> posts = findPostsByUser(user);
    int totalLikes = 0;
    for (Post post : posts) {
      totalLikes += post.getLikedByUsers().size();
    }
    return totalLikes;
  }

}
