package persistence;

import core.Post;
import core.User;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import persistence.hibernate.HibernateRepository;

// This JavaDoc comment was generated by Github Copilot
/**
 * The OrmPostRepository class provides an implementation of the PostRepository
 * interface using Hibernate for database operations.
 */
public class OrmPostRepository extends HibernateRepository implements PostRepository {
  @Override
  public void deleteById(Long id) {
    entityManagerFactory.runInTransaction(entityManager -> {
      Post post = entityManager.find(Post.class, id);
      if (post != null) {
        entityManager.remove(post);
      }
    });
  }

  @Override
  public boolean existsById(Long id) {
    return entityManagerFactory.callInTransaction(entityManager -> {
      return entityManager.find(Post.class, id) != null;
    });
  }

  @Override
  public List<Post> findAll() {
    return this.findAll(false);
  }

  @Override
  public List<Post> findAll(boolean withRelations) {
    if (withRelations) {
      return entityManagerFactory.callInTransaction(entityManager -> {
        List<Post> posts = entityManager
            .createQuery("FROM Post p LEFT JOIN FETCH p.likedByUsers", Post.class).getResultList();
        return posts;
      });
    }

    return entityManagerFactory.callInTransaction(entityManager -> {
      List<Post> posts = entityManager.createQuery("SELECT p FROM Post p", Post.class)
          .getResultList();
      return posts;
    });
  }

  @Override
  public Optional<Post> findById(Long id) {
    return this.findById(id, false);
  }

  @Override
  public Optional<Post> findById(Long id, boolean withRelations) {
    if (withRelations) {
      return entityManagerFactory.callInTransaction(entityManager -> {
        var graph = entityManager.createEntityGraph(Post.class);
        graph.addSubgraph("likedByUsers");
        return Optional.ofNullable(entityManager.find(graph, id));
      });
    }

    return entityManagerFactory.callInTransaction(entityManager -> {
      Post post = entityManager.find(Post.class, id);
      return Optional.ofNullable(post);
    });
  }

  @Override
  public Post save(Post post) {
    entityManagerFactory.runInTransaction(entityManager -> {
      entityManager.persist(post);
    });
    return post;
  }

  @Override
  public Post update(Post post) {
    return entityManagerFactory.callInTransaction(entityManager -> {
      Post managedPost = entityManager.find(Post.class, post.getId());
      if (managedPost != null) {
        managedPost.setContent(post.getContent());

        // Sync liked users properly
        managedPost.setLikedByUsers(post.getLikedByUsers());
        managedPost.setLikes(post.getLikes());
      }
      return managedPost;
    });
  }

  @Override
  public Post likePost(Post post, User user) {
    return entityManagerFactory.callInTransaction(entityManager -> {
      HashSet<User> likedByUsers = new HashSet<>(post.getLikedByUsers());
      if (likedByUsers.contains(user)) {
        likedByUsers.remove(user);
      } else {
        likedByUsers.add(user);
      }
      post.setLikedByUsers(likedByUsers);
      post.setLikes(likedByUsers.size());
      return entityManager.merge(post);
    });
  }
}
