package persistence;

import core.Post;
import core.User;
import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.CriteriaQuery;
import jakarta.persistence.criteria.CriteriaUpdate;
import jakarta.persistence.criteria.Root;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import org.hibernate.query.criteria.JpaExpression;
import persistence.hibernate.HibernateRepository;

// This JavaDoc comment was generated by Github Copilot
/**
 * The OrmPostRepository class provides an implementation of the PostRepository
 * interface using Hibernate for database operations.
 */
public class OrmPostRepository extends HibernateRepository implements PostRepository {
  @Override
  public void deleteById(Long id) {
    entityManagerFactory.runInTransaction(entityManager -> {
      Post post = entityManager.find(Post.class, id);
      if (post == null) {
        return;
      }

      if (post.getType() == Post.Type.RETWEET) {
        Post originalPost = post.getOriginalPost();
        if (originalPost != null) {
          originalPost.setReTweets(originalPost.getReTweets() - 1);
          entityManager.merge(originalPost);
        }
      } else {
        CriteriaUpdate<Post> update = criteriaBuilder.createCriteriaUpdate(Post.class);
        Root<Post> root = update.from(Post.class);
        JpaExpression<Post> nullPost = criteriaBuilder.nullLiteral(Post.class);

        // Set the update clause
        update.set("originalPost", nullPost);

        // Set the where clause
        update.where(root.get("originalPost").equalTo(post));

        // Execute the update
        entityManager.createQuery(update).executeUpdate();
      }

      entityManager.remove(post);
    });
  }

  @Override
  public boolean existsById(Long id) {
    return entityManagerFactory.callInTransaction(entityManager -> {
      return entityManager.find(Post.class, id) != null;
    });
  }

  @Override
  public List<Post> findAll() {
    return this.findAll(false);
  }

  @Override
  public List<Post> findAll(boolean withRelations) {
    CriteriaQuery<Post> query = criteriaBuilder.createQuery(Post.class);
    Root<Post> post = query.from(Post.class);
    query.select(post);

    return entityManagerFactory.callInTransaction(entityManager -> {
      if (withRelations) {
        post.fetch("likedByUsers", jakarta.persistence.criteria.JoinType.LEFT);
      }

      List<Post> posts = entityManager.createQuery(query).getResultList();
      return posts;
    });
  }

  @Override
  public Optional<Post> findById(Long id) {
    return this.findById(id, false);
  }

  @Override
  public Optional<Post> findById(Long id, boolean withRelations) {
    CriteriaQuery<Post> query = criteriaBuilder.createQuery(Post.class);
    Root<Post> post = query.from(Post.class);
    query.select(post).where(post.get("id").equalTo(id));

    return entityManagerFactory.callInTransaction(entityManager -> {
      if (withRelations) {
        post.fetch("likedByUsers", jakarta.persistence.criteria.JoinType.LEFT);
      }
      Post postResult = entityManager.createQuery(query).getSingleResultOrNull();
      return Optional.ofNullable(postResult);
    });
  }

  @Override
  public Post save(Post post) {
    entityManagerFactory.runInTransaction(entityManager -> {
      entityManager.persist(post);
    });
    return post;
  }

  @Override
  public Post update(Post post) {
    return entityManagerFactory.callInTransaction(entityManager -> {
      Post managedPost = entityManager.find(Post.class, post.getId());
      if (managedPost != null) {
        managedPost.setContent(post.getContent());

        // Sync liked users properly
        managedPost.setLikedByUsers(post.getLikedByUsers());
        managedPost.setLikes(post.getLikes());
        managedPost.setReTweets(post.getReTweets());
      }
      return managedPost;
    });
  }

  @Override
  public Post likePost(Post post, User user) {
    return entityManagerFactory.callInTransaction(entityManager -> {
      HashSet<User> likedByUsers = new HashSet<>(post.getLikedByUsers());
      if (likedByUsers.contains(user)) {
        likedByUsers.remove(user);
      } else {
        likedByUsers.add(user);
      }
      post.setLikedByUsers(likedByUsers);
      post.setLikes(likedByUsers.size());
      return entityManager.merge(post);
    });
  }

  @Override
  public Post updateRetweetCount(Post post) {
    return entityManagerFactory.callInTransaction(session -> {
      Post managedPost = session.find(Post.class, post.getId());
      if (managedPost != null) {
        managedPost.setReTweets(post.getReTweets());
      }
      return managedPost;
    });
  }

  @Override
  public List<Post> findByUser(User user) {
    return this.findByUser(user, false);
  }

  @Override
  public List<Post> findByUser(User user, boolean withRelations) {
    return entityManagerFactory.callInTransaction(entityManager -> {
      CriteriaBuilder cb = entityManager.getCriteriaBuilder();
      CriteriaQuery<Post> query = cb.createQuery(Post.class);
      Root<Post> post = query.from(Post.class);

      if (withRelations) {
        post.fetch("likedByUsers", jakarta.persistence.criteria.JoinType.LEFT);
      }

      query.select(post).where(cb.equal(post.get("author"), user));
      return entityManager.createQuery(query).getResultList();
    });
  }
}
