package persistence;

import core.User;
import jakarta.persistence.criteria.CriteriaQuery;
import jakarta.persistence.criteria.Root;
import java.util.List;
import java.util.Optional;
import persistence.hibernate.HibernateRepository;

// This JavaDoc comment was generated by Github Copilot
/**
 * The OrmUserRepository class provides an implementation of the UserRepository
 * interface using Hibernate for persistence operations.
 */
public class OrmUserRepository extends HibernateRepository implements UserRepository {
  @Override
  public void deleteById(Long id) {
    entityManagerFactory.runInTransaction(entityManager -> {
      User user = entityManager.find(User.class, id);
      if (user != null) {
        entityManager.remove(user);
      }
    });
  }

  @Override
  public boolean existsById(Long id) {
    return entityManagerFactory.callInTransaction(entityManager -> {
      return entityManager.find(User.class, id) != null;
    });
  }

  // createQuery usage inspired by Hibernate Getting Started guide
  // See: http://docs.jboss.org/hibernate/orm/7.1/quickstart/html_single/
  // Start createQuery usage
  @Override
  public List<User> findAll() {
    return entityManagerFactory.callInTransaction(entityManager -> {
      CriteriaQuery<User> query = criteriaBuilder.createQuery(User.class);
      query.from(User.class);
      return entityManager.createQuery(query).getResultList();
    });
  }

  @Override
  public Optional<User> findById(Long id) {
    return entityManagerFactory.callInTransaction(entityManager -> {
      User user = entityManager.find(User.class, id);
      return Optional.ofNullable(user);
    });
  }

  @Override
  public Optional<User> findByUsername(String username) {
    return entityManagerFactory.callInTransaction(entityManager -> {
      CriteriaQuery<User> query = criteriaBuilder.createQuery(User.class);
      Root<User> user = query.from(User.class);
      query.select(user).where(criteriaBuilder.equal(user.get("username"), username));

      User userResult = entityManager.createQuery(query).getSingleResultOrNull();
      return Optional.ofNullable(userResult);
    });
  }
  // End createQuery usage

  @Override
  public User save(User user) {
    entityManagerFactory.runInTransaction(entityManager -> {
      entityManager.persist(user);
    });
    return user;
  }

  @Override
  public User update(User user) {
    entityManagerFactory.runInTransaction(entityManager -> {
      entityManager.merge(user);
    });
    return user;
  }
}
