package persistence;

import core.Post;
import java.util.List;
import java.util.Optional;

// This JavaDoc comment was generated by Github Copilot
/** Repository for managing Post entities. */
public interface PostRepository {

  // This JavaDoc comment was generated by Github Copilot
  /** Finds a post by ID. */
  Optional<Post> findById(Long id);

  // This JavaDoc comment was generated by Github Copilot
  /** Returns all posts. */
  List<Post> findAll();

  // This JavaDoc comment was generated by Github Copilot
  /** Saves a new post. */
  Post save(Post post);

  // This JavaDoc comment was generated by Github Copilot
  /** Updates an existing post. */
  Post update(Post post);

  // This JavaDoc comment was generated by Github Copilot
  /** Deletes a post by ID. */
  void deleteById(Long id);

  // This JavaDoc comment was generated by Github Copilot
  /** Checks if a post exists by ID. */
  boolean existsById(Long id);
}
