package persistence;

import core.Post;
import core.User;
import java.util.List;
import java.util.Optional;

//  Most JavaDoc comments in this file were generated by Github Copilot
/** Repository for managing Post entities. */
public interface PostRepository {
  /** Returns the post by id, if it exists. */
  Optional<Post> findById(Long id);

  /** Returns the post by id, with their respective likes, if the post exists. */
  Optional<Post> findById(Long id, boolean withRelations);

  /** Returns all posts. */
  List<Post> findAll();

  /** Returns all posts with their respective likes. */
  List<Post> findAll(boolean withRelations);

  /** Saves a new post. */
  Post save(Post post);

  /** Updates an existing post. */
  Post update(Post post);

  /** Deletes a post by ID. */
  void deleteById(Long id);

  /** Checks if a post exists by ID. */
  boolean existsById(Long id);

  /** Likes/unlikes the @param post by the @param user . */
  Post likePost(Post post, User user);

  /** Updates retweet counter for @param post */
  Post updateRetweetCount(Post post);

}
