package persistence;

import core.User;
import java.util.List;
import java.util.Optional;

// This JavaDoc comment was generated by Github Copilot
/**
 * Repository for managing User entities.
 */
public interface UserRepository {

  // This JavaDoc comment was generated by Github Copilot
  /** Finds a user by ID. */
  Optional<User> findById(Long id);

  // This JavaDoc comment was generated by Github Copilot
  /** Returns all users. */
  List<User> findAll();

  // This JavaDoc comment was generated by Github Copilot
  /** Saves a new user. */
  User save(User user);

  // This JavaDoc comment was generated by Github Copilot
  /** Updates an existing user. */
  User update(User user);

  // This JavaDoc comment was generated by Github Copilot
  /** Deletes a user by ID. */
  void deleteById(Long id);

  // This JavaDoc comment was generated by Github Copilot
  /** Checks if a user exists by ID. */
  boolean existsById(Long id);

  // This JavaDoc comment was generated by Github Copilot
  /** Finds a user by username. */
  Optional<User> findByUsername(String username);
}
