package ui;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.io.IOException;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import ui.config.AppConfig;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

// This JavaDoc comment was generated by Github Copilot
/**
 * Main JavaFX application class. Integrates Spring Boot context and loads
 * initial UI.
 */
public class App extends Application {
  private static Scene scene;

  private static ConfigurableApplicationContext springContext;

  @Override
  public void init() throws Exception {
    setSpringContext(new AnnotationConfigApplicationContext(AppConfig.class));
  }

  @Override
  public void start(Stage stage) throws Exception {
    FXMLLoader loader = new FXMLLoader(getClass().getResource("login.fxml"));
    loader.setControllerFactory(springContext::getBean);
    Parent root = loader.load();
    Scene newScene = new Scene(root, 1280, 720);
    stage.setTitle("Twitter Clone");
    stage.setScene(newScene);
    stage.show();
    setScene(newScene);
  }

  @Override
  public void stop() throws Exception {
    springContext.close();
    Platform.exit();
  }

  private static void setSpringContext(ConfigurableApplicationContext newSpringContext) {
    springContext = newSpringContext;
  }

  @SuppressFBWarnings(value = "MS_EXPOSE_REP", justification = "We need to expose "
      + "the spring context.")
  public static ConfigurableApplicationContext getSpringContext() {
    return springContext;
  }

  private static void setScene(Scene newScene) {
    scene = newScene;
  }

  /**
   * Sets the root of the JavaFX scene from an FXML file.
   *
   * @param fxml the name of the FXML file (e.g. 'fileName.fxml') to load and set
   *             as the root.
   * @throws IOException if the specified FXML file cannot be found or loaded.
   */
  public static void setRoot(String fxml) throws IOException {
    FXMLLoader loader = new FXMLLoader(App.class.getResource(fxml));
    loader.setControllerFactory(springContext::getBean);
    scene.setRoot(loader.load());
  }

  // This JavaDoc comment was generated by Github Copilot
  /** Launches the JavaFX application. */
  public static void main(String[] args) {
    launch(args);
  }
}
