package ui;

import core.payload.response.PostResponse;
import java.io.IOException;
import javafx.fxml.FXML;
import javafx.scene.control.ListView;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import service.PostService;

// This JavaDoc comment was generated by Github Copilot
/**
 * Controller for the main feed view. Displays posts and handles navigation.
 */
@Component
public class FeedController {
  PostService postService;

  // This JavaDoc comment was generated by Github Copilot
  /**
   * Constructs the controller with required services.
   *
   * @param postService the post service
   */
  @Autowired
  public FeedController(PostService postService) {
    this.postService = postService;
  }

  @FXML
  private ListView<PostResponse> feedList;

  // This JavaDoc comment was generated by Github Copilot
  /** Initializes the feed list view and populates posts. */
  @FXML
  public void initialize() {
    // Disable the higlight on selectio of posts
    feedList.setSelectionModel(null);
    feedList.setFocusTraversable(false);

    // Use custom cell factory to display each Post using the post.fxml layout and
    // PostCell class
    feedList.setCellFactory(listView -> new PostCell());

    feedList.getItems().setAll(postService.getAllPosts());
  }

  @FXML
  @SuppressWarnings("unused")
  private void switchToMakeNewPost() throws IOException {
    App.setRoot("makeNewPost.fxml");
  }

  @FXML
  @SuppressWarnings("unused")
  private void switchToLogin() throws IOException {
    App.setRoot("login.fxml");
  }

}
