package ui;

import java.io.IOException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextArea;
import service.PostService;

import core.Post;
import core.User;
import service.UserService;
import service.PostService;

@Component
public class MakeNewPostController {
  private final PostService postService;
  private final UserService userService;

  @Autowired
  public MakeNewPostController(PostService postService, UserService userService) {
    this.postService = postService;
    this.userService = userService;
  }

  @FXML
  private TextArea postText; 

  @FXML
  private Button publishBtn;

  @FXML
  private Button backBtn;
  

  /*
   * Function below is generated by openAI GPT-5 model.
   * However, it is altered to fit our classes and needs
   */
  @FXML
  @SuppressWarnings("unused")
  private void publishPost() throws IOException {
    String content = postText.getText();

    if (content == null || content.isBlank()) {
      System.out.println("Content cannot be empty");
      return;
    }

    if (content.length() > Post.MAX_CONTENT_LENGTH) {
      System.out.println("Content too long (" + content.length() + ")");
      return;
    }

    User user = userService.getLoggedInUser();
    String id = java.util.UUID.randomUUID().toString();
    Post post = new Post(user, content, id);

    postService.createPost(post);    

    switchToFeed();
  }


  @FXML
  @SuppressWarnings("unused")
  private void switchToFeed() throws IOException {
    App.setRoot("feed.fxml");
  }
}
