package ui;

import core.Post;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonBar;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Dialog;
import javafx.scene.control.Label;
import javafx.scene.control.TextArea;

import java.io.IOException;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import service.PostService;
import service.UserService;

// This JavaDoc comment was generated by Github Copilot
/**
 * Controller for individual post UI component. Binds Post data to the post.fxml
 * labels.
 */
@Component
@Scope("prototype") // Tells springboot to create individual PostController class for posts
public class PostController {
  private final PostService postService;
  private final UserService userService;

  /** Controller injects the necessary services. */
  @Autowired
  @SuppressFBWarnings(value = "EI_EXPOSE_REP2", justification = "We need to inject the "
      + "userService and postService.")
  public PostController(PostService postService, UserService userService) {
    this.postService = postService;
    this.userService = userService;
  }

  @FXML
  private Label displayNameLabel;
  @FXML
  private Label usernameLabel;
  @FXML
  private Label contentLabel;
  @FXML
  private Button likeBtn;
  @FXML
  private Button retweetBtn;

  @SuppressFBWarnings(value = "EI_EXPOSE_REP2", justification = "The Post is used in a "
      + "tightly scoped controller context where mutation is safe and intentional.")
  private Post currentPost;

  // This JavaDoc comment was generated by Github Copilot
  /** Sets the Post data to the UI labels. */
  @FXML
  public void setData(Post post) {
    this.currentPost = post;

    displayNameLabel.setText(post.getAuthor().getDisplayName());
    usernameLabel.setText("@" + post.getAuthor().getUsername());
    contentLabel.setText(post.getContent());
    likeBtn.setText(post.getLikes() + " 👍");
    retweetBtn.setText(post.getReTweets() + " 🔄");

    if (post.likedByUser(userService.getLoggedInUser())) {
      likeBtn.setStyle("-fx-text-fill: blue;");
    }
    // updateLikes();
    // if (post.reTweetedByUser(userService.getLoggedInUser()))
    // retweetBtn.setStyle("-fx-text-fill: cyan;");
  }

  /** Updates the likes UI elements when the like button is pressed. */
  @FXML
  public void updateLikes() {
    if (currentPost == null) {
      return;
    }

    postService.likePost(currentPost, userService.getLoggedInUser());
    postService.update(currentPost);
    likeBtn.setText(currentPost.getLikes() + " 👍");

    if (currentPost.likedByUser(userService.getLoggedInUser())) {
      likeBtn.setStyle("-fx-text-fill: blue;");
    } else {
      likeBtn.setStyle("-fx-text-fill: black;");
    }

  }

  /** Updates the retweet UI elements when the retweet button is pressed. */
  @FXML
  public void updateRetweets() {
    if (currentPost == null)
      return;

    // Create dialog
    Dialog<String> dialog = new Dialog<>();
    dialog.setTitle("Retweet");
    dialog.setHeaderText("Add an optional message and confirm your retweet");
    // Buttons
    ButtonType retweetBtnType = new ButtonType("Retweet", ButtonBar.ButtonData.OK_DONE);
    dialog.getDialogPane().getButtonTypes().addAll(retweetBtnType, ButtonType.CANCEL);

    // Content: a TextArea
    TextArea messageArea = new TextArea();
    messageArea.setPromptText("Add a message (optional)");
    messageArea.setWrapText(true);
    messageArea.setPrefRowCount(3);

    dialog.getDialogPane().setContent(messageArea);

    // Convert result
    dialog.setResultConverter(dialogButton -> {
      if (dialogButton == retweetBtnType) {
        return messageArea.getText().trim(); // may be empty
      }
      return null;
    });

    Optional<String> result = dialog.showAndWait();
    result.ifPresent(msg -> onConfirmRetweet(msg));
  }

  private void onConfirmRetweet(String msg) {
    // var user = userService.getLoggedInUser();
    // Post retweetPost = new Post(user, "", null);
    // boolean nowRetweeted = postService.createRetweet(currentPost, retweetPost); // implement this

    // postService.update(currentPost);
    // retweetBtn.setText(currentPost.getReTweets() + " 🔄");
    // retweetBtn.setStyle(nowRetweeted ? "-fx-text-fill: cyan;" : "-fx-text-fill: black;");
  }

}
