package ui;

import core.payload.response.PostResponse;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.ButtonType;
import javafx.scene.control.ListCell;
import javafx.scene.layout.HBox;

// This class is based on the example from this StackOverflow post:
// https://stackoverflow.com/a/77508842

// This JavaDoc comment was generated by Github Copilot
/**
 * Custom ListCell for displaying Post objects in a ListView. and binds data via
 * PostController.
 */
public class PostCell extends ListCell<PostResponse> {
  private HBox postItem;
  private PostController postController;

  /**
   * Constructs a PostCell object.
   */
  public PostCell() {
    try {
      FXMLLoader loader = new FXMLLoader(App.class.getResource("post.fxml"));
      loader.setControllerFactory(App.getSpringContext()::getBean);
      postItem = loader.load();
      postController = loader.getController();
    } catch (Exception e) {
      e.printStackTrace();
      Alert alert = new Alert(AlertType.ERROR, "Could not load post view.", ButtonType.OK);
      alert.show();
    }
  }

  @Override
  protected void updateItem(PostResponse post, boolean empty) {
    super.updateItem(post, empty);
    if (empty || post == null) {
      setText(null);
      setGraphic(null);
    } else {
      postController.setData(post);
      setGraphic(postItem);
    }
    // Removes the default alternating background color for filled cells
    setStyle("-fx-background-color: transparent;");
  }
}
