package ui;

import core.payload.response.PostResponse;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import org.springframework.stereotype.Component;

// This JavaDoc comment was generated by Github Copilot
/**
 * Controller for individual post UI component. Binds Post data to the post.fxml
 * labels.
 */
@Component
public class PostController {

  @FXML
  private Label displayNameLabel;
  @FXML
  private Label usernameLabel;
  @FXML
  private Label contentLabel;

  // This JavaDoc comment was generated by Github Copilot
  /** Sets the Post data to the UI labels. */
  public void setData(PostResponse post) {
    displayNameLabel.setText(post.author().displayName());
    usernameLabel.setText("@" + post.author().username());
    contentLabel.setText(post.content());
  }
}
