package ui;

import java.io.IOException;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import core.payload.response.PostResponse;
import core.payload.response.UserResponse;
import core.util.NumberFormatter;
import javafx.beans.binding.BooleanBinding;
import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonBar;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Dialog;
import javafx.scene.control.Label;
import javafx.scene.control.TextArea;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import service.PostService;
import service.UserService;
import ui.util.AppIcons;

// This JavaDoc comment was generated by Github Copilot
/**
 * Controller for individual post UI component. Binds Post data to the post.fxml
 * labels.
 */
@Component
@Scope("prototype") // Tells springboot to create individual PostController class for posts
public class PostController {
  @Autowired
  private PostService postService;

  @Autowired
  private UserService userService;

  // -------- post.fxml (regular) --------
  @FXML
  private Label displayNameLabel;
  @FXML
  private Label usernameLabel;
  @FXML
  private Label contentLabel; // ALSO used by retweetPost.fxml as the *outer* (retweeter) message
  @FXML
  private ImageView likeImageView;
  @FXML
  @SuppressWarnings("unused")
  private ImageView retweetImageView;
  @FXML
  private Text likeBtnText;
  @FXML
  private Text retweetBtnText;
  @FXML
  @SuppressWarnings("unused")
  private Button deleteBtn;

  // -------- retweetPost.fxml (outer retweet header) --------
  @FXML
  private Label displayNameLabelRetweet; // retweeter name
  @FXML
  private Label usernameLabelRetweet; // retweeter username

  // -------- retweetPost.fxml (inner original content) --------
  @FXML
  private Button retweetBtn;

  @FXML
  private Label contentLabel1; // original post content

  private PostResponse currentPost;

  private boolean isOwn(PostResponse p) {
    UserResponse me = userService.getLoggedInUser();
    if (me == null || p == null || p.author() == null) {
      return false;
    }
    return me.id() != null && me.id().equals(p.author().id());
  }

  // This JavaDoc comment was generated by Github Copilot
  /** Sets the Post data to the UI labels. */
  @FXML
  public void setData(PostResponse post) {
    this.currentPost = post;

    boolean isRetweet = post.originalPostId() != null;

    if (likeBtnText != null) {
      likeBtnText.setText(NumberFormatter.formatCount(post.likes()));
      if (post.likedByUser(userService.getLoggedInUser().id())) {
        likeBtnText.setStyle("-fx-text-fill: #0078ae;");
        likeImageView.setImage(AppIcons.LIKE_ON);
      } else {
        likeBtnText.setStyle("-fx-text-fill: black;");
        likeImageView.setImage(AppIcons.LIKE_OFF);
      }
    }

    if (!isRetweet) {
      // ===== Regular post (post.fxml) =====
      if (displayNameLabel != null) {
        displayNameLabel.setText(post.author().displayName());
      }
      if (usernameLabel != null) {
        usernameLabel.setText("@" + post.author().username());
      }
      if (contentLabel != null) {
        contentLabel.setText(post.content());
      }

      if (retweetBtn != null) {
        boolean own = isOwn(post);
        retweetBtnText.setText(NumberFormatter.formatCount(post.reTweets()));
        retweetBtn.setVisible(!own);
        retweetBtn.setManaged(!own);
      }
      return;
    }

    // Outer header: retweeter info
    if (displayNameLabelRetweet != null) {
      displayNameLabelRetweet.setText(post.author().displayName());
    }
    if (usernameLabelRetweet != null) {
      usernameLabelRetweet.setText("@" + post.author().username());
    }

    // Outer message (retweeter's optional comment) goes into contentLabel
    if (contentLabel != null) {
      String comment = post.content() == null ? "" : post.content();
      boolean show = !comment.isBlank();
      contentLabel.setText(comment);
      contentLabel.setVisible(show);
      contentLabel.setManaged(show); // collapse space when there is no comment
    }

    // ===== Retweet layout (retweetPost.fxml) =====
    Long originalId = post.originalPostId();
    PostResponse original = postService.getPostById(originalId).orElse(null);

    // Inner card: original post info (names reuse the same ids as post.fxml)
    if (original != null) {
      if (displayNameLabel != null) {
        displayNameLabel.setText(original.author().displayName());
      }
      if (usernameLabel != null) {
        usernameLabel.setText("@" + original.author().username());
      }

      if (contentLabel1 != null) {
        contentLabel1.setText(original.content());
      } else if (contentLabel != null) {
        // Fallback if your inner card uses contentLabel instead of contentLabel1
        contentLabel.setText(original.content());
        contentLabel.setVisible(true);
        contentLabel.setManaged(true);
      }
    } else {
      // Defensive fallback (shouldn't happen): show retweet as a normal post
      if (displayNameLabel != null) {
        displayNameLabel.setText(post.author().displayName());
      }
      if (usernameLabel != null) {
        usernameLabel.setText("@" + post.author().username());
      }
      if (contentLabel1 != null) {
        contentLabel1.setText(post.content());
      }
      if (contentLabel != null) {
        contentLabel.setText(post.content());
        contentLabel.setVisible(true);
        contentLabel.setManaged(true);
      }
    }
  }

  /** Updates the likes UI elements when the like button is pressed. */
  @FXML
  public void updateLikes() {
    if (currentPost == null || likeBtnText == null) {
      return;
    }

    currentPost = postService.likePost(currentPost.id());
    // postService.update(currentPost);

    likeBtnText.setText(NumberFormatter.formatCount(currentPost.likes()));

    if (currentPost.likedByUser(userService.getLoggedInUser().id())) {
      likeBtnText.setStyle("-fx-text-fill: #0078ae;");
      likeImageView.setImage(AppIcons.LIKE_ON);
    } else {
      likeBtnText.setStyle("-fx-text-fill: black;");
      likeImageView.setImage(AppIcons.LIKE_OFF);

      postService.notifyPostUpdated();
    }
  }

  // Method below is generated by chatGPT

  /** Updates the retweet UI elements when the retweet button is pressed. */
  @FXML
  public void updateRetweets() {
    if (currentPost == null || retweetBtn == null) {
      return;
    }

    final int MAX_MESSAGE_LEN = 280; // ⬅️ adjust as needed

    Dialog<String> dialog = new Dialog<>();
    dialog.setTitle("Retweet");
    dialog.setHeaderText("Add an optional message and confirm your retweet");

    ButtonType retweetBtnType = new ButtonType("Retweet", ButtonBar.ButtonData.OK_DONE);
    dialog.getDialogPane().getButtonTypes().addAll(retweetBtnType, ButtonType.CANCEL);

    TextArea messageArea = new TextArea();
    messageArea.setPromptText("Add a message (optional)");
    messageArea.setWrapText(true);
    messageArea.setPrefRowCount(3);

    Label counter = new Label();
    counter.textProperty().bind(javafx.beans.binding.Bindings.format("%d / %d",
        javafx.beans.binding.Bindings.length(messageArea.textProperty()), MAX_MESSAGE_LEN));
    BooleanBinding overLimit = javafx.beans.binding.Bindings.greaterThan(
        javafx.beans.binding.Bindings.length(messageArea.textProperty()), MAX_MESSAGE_LEN);
    counter.textFillProperty().bind(javafx.beans.binding.Bindings.when(overLimit)
        .then(javafx.scene.paint.Color.RED).otherwise(javafx.scene.paint.Color.GRAY));
    BooleanBinding isEmpty = javafx.beans.binding.Bindings.createBooleanBinding(
        () -> messageArea.getText().trim().isEmpty(), messageArea.textProperty());

    HBox counterBox = new HBox(counter);
    counterBox.setAlignment(javafx.geometry.Pos.BASELINE_RIGHT);
    counterBox.setPadding(new javafx.geometry.Insets(4, 0, 0, 0));

    VBox content = new VBox(8, messageArea, counterBox);
    content.setPrefWidth(420);
    dialog.getDialogPane().setContent(content);

    Node okButton = dialog.getDialogPane().lookupButton(retweetBtnType);
    okButton.disableProperty().bind(overLimit.or(isEmpty));

    javafx.application.Platform.runLater(messageArea::requestFocus);

    dialog.setResultConverter(btn -> (btn == retweetBtnType) ? messageArea.getText().trim() : null);

    Optional<String> result = dialog.showAndWait();
    result.ifPresent(this::onConfirmRetweetSafe);
  }

  private void onConfirmRetweetSafe(String msg) {
    UserResponse user = userService.getLoggedInUser();

    if (user.id().equals(currentPost.author().id())) {
      return;
    }

    if (msg == null) {
      msg = " ";
    }

    postService.createPost(msg, currentPost.id());

    if (retweetBtn != null) {
      retweetBtn.setText(currentPost.reTweets() + " 🔄");
      retweetBtn.setStyle("-fx-text-fill: cyan;");
    }

    try {
      App.setRoot("feed.fxml");
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  @FXML
  public void deletePost() {
    throw new UnsupportedOperationException("Not implemented yet");
  }
}
