@startuml classDiagram
skinparam linetype ortho
skinparam nodesep 130

class User {
  - Long id
  - String username
  - String displayName
  - String password
  - List<Post> posts
  + User()
  + User(Long, String, String, String)
  + Long getId()
  + void setId(Long)
  + String getUsername()
  + void setUsername(String)
  + String getDisplayName()
  + void setDisplayName(String)
  + String getPassword()
  + void setPassword(String)
}

class Post {
  - Long id
  - User author
  - String content
  - int likes
  - int reTweets
  - int commentsAmount
  + Post()
  + Post(User, String, Long)
  + String getContent()
  + void setContent(String)
  + int getLikes()
  + void setLikes(int)
  + int getReTweets()
  + void setReTweets(int)
  + int getCommentsAmount()
  + void setCommentsAmount(int)
  + Long getId()
  + void setId(Long)
  + User getAuthor()
  + void setAuthor(User)
  + int getMaxContentLenght()
}

User "1" o-left-- "*" Post : posts
Post "*" --> "1" User : author

@enduml
