@startuml packageDiagram
skinparam linetype ortho
skinparam padding 7
skinparam ArrowFontSize 16
skinparam ArrowThickness 3
skinparam nodesep 40
left to right direction

package "REST Client" as REST_CLIENT #FFF3E0{
  package "UI (ui)" as UI_JavaFX #FFFFFF{
    [App]
    [FeedController]
    [LoginController]
    [MakeNewPostController]
    [PostController]
    [ProfileController]
    [PostCell]
    [util.AppIcons]
  }

  package "Client Services (service)" as Client_Services #FFFFFF{
    [ApiClientService]
    [PostService]
    [UserService]
  }
}

package "REST Server" as REST_SERVER #FFF3E0{
  package "API Layer (api)" as API_Layer #FFFFFF{
    [ApiApplication]
    [controller.PostController]
    [controller.UserController]
    [controller.AuthController]
    [service.PostService]
    [service.UserService]
    [service.UserDetailsServiceImpl]
    [service.JwtUtilsService]
    [config.AppConfig]
    [config.SecurityConfig]
    [config.AuthTokenFilter]
    [utils.JwtKeyGenerator]
  }

  package "Persistence (persistence)" as Persistence #FFFFFF{
    [PostRepository]
    [UserRepository]
    [OrmPostRepository]
    [OrmUserRepository]
    [JsonPostRepository]
    [JsonUserRepository]
    [HibernateRepository]
    [JsonRepository]
  }
}

package "Core (core)" as Core #f0f7ff{
    [Post]
    [User]
    package payload #FFFFFF {
        package request #FFFFFF {
            [CreatePostRequest]
            [LoginRequest]
            [UpdateUserRequest]
        }
        package response #FFFFFF {
            [PostResponse]
            [UserResponse]
            [LoginResponse]
        }
    }
}

database "SQLite\nDatabase" as SQLite_DB


UI_JavaFX --> Client_Services :    Uses \nservices
Client_Services -right-> Core : Uses/returns DTOs
Client_Services <--> API_Layer : \nHTTP \nrequests/responses


Persistence <-- API_Layer : \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSaving data                             \n(service -> repository)                            .
Persistence --> Core : \n\nDepends on
API_Layer --> Core : \n\n\n\n\n\n\n\n\n\n\nBuilds response DTOs
API_Layer --> Core : \n\n\n\n\n\n\n\n\n\n\n\n\n\n\nReads domain model
Persistence --> SQLite_DB : \n\n\n\n\n\n\n\nReads/writes

legend right
API_Layer: controllers -> services (controllers call services)
end legend

@enduml
