package persistence.json;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import persistence.hibernate.HibernateRepository;

// This JavaDoc comment was generated by Github Copilot
/**
 * Repository for storing/retrieving objects in JSON files.
 *
 * @param <T> type of objects stored
 * @deprecated Use {@link HibernateRepository} instead (switched to
 *             SQLite/Hibernate).
 */
@Deprecated
public class JsonRepository<T> {
  private final ObjectMapper objectMapper;
  private final Path filePath;
  private final TypeReference<List<T>> typeReference;

  // This JavaDoc comment was generated by Github Copilot
  /** Constructs a JsonRepository with the given file path and type reference. */
  public JsonRepository(Path filePath, TypeReference<List<T>> typeReference) {
    this.objectMapper = new ObjectMapper();
    this.objectMapper.findAndRegisterModules();

    this.filePath = filePath;
    this.typeReference = typeReference;
  }

  /**
   * Loads objects from the JSON file.
   *
   * @return The objects, or an empty list if the file does not exist or is empty.
   * @throws IOException if an IO error occurs while reading the file.
   */
  public List<T> load() throws IOException {
    File file = this.filePath.toFile();
    if (!file.exists() || file.length() == 0) {
      return new ArrayList<>();
    }

    return this.objectMapper.readValue(file, this.typeReference);
  }

  /**
   * Saves the given list of objects to the JSON file.
   *
   * @param data the list of objects to serialize and save.
   * @throws IOException if an IO error occurs while writing to the file.
   */
  public void save(List<T> data) throws IOException {
    this.objectMapper.writeValue(this.filePath.toFile(), data);
  }
}
