package persistence.hibernate;

import static jakarta.persistence.Persistence.createEntityManagerFactory;

import core.Post;
import core.User;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.criteria.CriteriaDelete;
import org.hibernate.SessionFactory;
import org.hibernate.query.criteria.HibernateCriteriaBuilder;

// Heavily inspired by Hibernate's Getting Started tutorial
// The EntityManagerFactory is instantiated in the same way in our project
// See: https://docs.hibernate.org/orm/7.1/quickstart/html_single/
/**
 * Provides a base repository class that sets up the EntityManagerFactory for
 * Hibernate database operations.
 */
public class HibernateRepository {
  protected EntityManagerFactory entityManagerFactory = createEntityManagerFactory(
      "twitter-clone-persistence-unit");

  protected HibernateCriteriaBuilder criteriaBuilder = entityManagerFactory
      .unwrap(SessionFactory.class).getCriteriaBuilder();

  // This JavaDoc comment was generated by Github Copilot
  /** Closes the EntityManagerFactory and releases Hibernate resources. */
  protected void tearDown() {
    entityManagerFactory.close();
  }

  /** Deletes all entries from all tables. */
  public void dropDatabase() {
    CriteriaDelete<Post> postQuery = criteriaBuilder.createCriteriaDelete(Post.class);
    postQuery.from(Post.class);
    CriteriaDelete<User> userQuery = criteriaBuilder.createCriteriaDelete(User.class);
    userQuery.from(User.class);

    entityManagerFactory.runInTransaction((entityManager) -> {
      entityManager.createQuery(postQuery).executeUpdate();
      entityManager.createQuery(userQuery).executeUpdate();
    });
  }
}
