package persistence.hibernate;

import static jakarta.persistence.Persistence.createEntityManagerFactory;

import jakarta.persistence.EntityManagerFactory;

// Heavily inspired by Hibernate's Getting Started tutorial
// The EntityManagerFactory is instantiated in the same way in our project
// See: https://docs.hibernate.org/orm/7.1/quickstart/html_single/
/**
 * Provides a base repository class that sets up the EntityManagerFactory for
 * Hibernate database operations.
 */
public class HibernateRepository {
  protected EntityManagerFactory entityManagerFactory = createEntityManagerFactory(
      "twitter-clone-persistence-unit");

  // This JavaDoc comment was generated by Github Copilot
  /** Closes the EntityManagerFactory and releases Hibernate resources. */
  protected void tearDown() {
    entityManagerFactory.close();
  }

  /** Deletes all entries from all tables. */
  public void dropDatabase() {
    entityManagerFactory.runInTransaction((entityManager) -> {
      entityManager.createQuery("DELETE FROM Post").executeUpdate();
      entityManager.createQuery("DELETE FROM User").executeUpdate();
    });
  }
}
