package service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

import core.Post;
import core.User;
import core.payload.request.CreatePostRequest;
import core.payload.response.PostResponse;
import core.payload.response.UserResponse;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicBoolean;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.web.reactive.function.client.WebClientResponseException;

// This JavaDoc comment was generated by Github Copilot
/**
 * Unit tests for PostService. Verifies retrieval and creation of posts with
 * mocks.
 */
@ExtendWith(MockitoExtension.class)
public class PostServiceTest {
  @Mock
  private ApiClientService apiClient;

  @InjectMocks
  private PostService postService;

  private User user;
  private Long postId;
  private Post post;

  @BeforeEach
  void setup() {
    this.user = new User(1L, "john", "John Pork", "pass");
    this.postId = 123L;
    this.post = new Post(this.user, "hello world", postId);
  }

  @Test
  void getPostByIdReturnsEmptyWhenNotFound() {
    WebClientResponseException exception = WebClientResponseException.create(404, "Not Found", null,
        null, null);
    when(apiClient.get(eq("/api/posts/" + postId), eq(PostResponse.class))).thenThrow(exception);
    assertTrue(postService.getPostById(postId).isEmpty());
  }

  @Test
  void getPostByIdReturnsPostWhenFound() {
    UserResponse fakeAuthor = new UserResponse(user.getId(), user.getUsername(),
        user.getDisplayName());
    PostResponse fakePost = new PostResponse(post.getId(), post.getContent(), post.getLikes(),
        post.getReTweets(), post.getCommentsAmount(), fakeAuthor, Set.of(), null);
    when(apiClient.get(eq("/api/posts/" + postId), eq(PostResponse.class))).thenReturn(fakePost);
    assertEquals(fakePost, postService.getPostById(postId).get());
  }

  @Test
  void createPostThrowsExceptionWhenNull() {
    String content = null;
    assertThrows(IllegalArgumentException.class, () -> postService.createPost(content, postId));
  }

  @Test
  void createPostWorks() {
    String content = "content";
    UserResponse fakeAuthor = new UserResponse(user.getId(), user.getUsername(),
        user.getDisplayName());
    PostResponse expectedResponse = new PostResponse(postId, content, 0, 0, 0, fakeAuthor, Set.of(),
        null);

    when(apiClient.post(eq("/api/posts"), eq(new CreatePostRequest(content, postId)),
        eq(PostResponse.class))).thenReturn(expectedResponse);

    PostResponse result = postService.createPost(content, postId);
    assertEquals(expectedResponse, result);
  }

  @Test
  void getAllPostsReturnsPosts() {
    UserResponse fakeAuthor = new UserResponse(user.getId(), user.getUsername(),
        user.getDisplayName());
    List<PostResponse> expectedPosts = List.of(
        new PostResponse(postId, "content1", 0, 0, 0, fakeAuthor, Set.of(), null),
        new PostResponse(postId + 1, "content2", 0, 0, 0, fakeAuthor, Set.of(), null));

    when(apiClient.get(eq("/api/posts"), eq(new ParameterizedTypeReference<List<PostResponse>>() {
    }))).thenReturn(expectedPosts);
    List<PostResponse> result = postService.getAllPosts();
    assertEquals(expectedPosts, result);
  }

  @Test
  void getAllPostsWithRelationsThrows() {
    assertThrows(UnsupportedOperationException.class, () -> postService.getAllPosts(true));
  }

  @Test
  void getPostByIdWithRelationsThrows() {
    assertThrows(UnsupportedOperationException.class, () -> postService.getPostById(postId, true));
  }

  @Test
  void postsByUserReturnsPostsByUser() {
    UserResponse fakeAuthor = new UserResponse(user.getId(), user.getUsername(),
        user.getDisplayName());
    List<PostResponse> expectedPosts = List
        .of(new PostResponse(postId, "content1", 0, 0, 0, fakeAuthor, Set.of(), null));

    when(apiClient.get(eq("/api/posts/mine"),
        eq(new ParameterizedTypeReference<List<PostResponse>>() {
        }))).thenReturn(expectedPosts);

    List<PostResponse> result = postService.postsByUser();
    assertEquals(expectedPosts, result);
  }

  @Test
  void postsByUserReturnsEmptyOnError() {
    WebClientResponseException exception = WebClientResponseException.create(401, "Unauthorized",
        null, null, null);

    when(apiClient.get(eq("/api/posts/mine"),
        eq(new ParameterizedTypeReference<List<PostResponse>>() {
        }))).thenThrow(exception);

    List<PostResponse> result = postService.postsByUser();
    assertTrue(result.isEmpty());
  }

  @Test
  void likePost() {
    UserResponse fakeAuthor = new UserResponse(user.getId(), user.getUsername(),
        user.getDisplayName());
    PostResponse expectedPost = new PostResponse(postId, "content", 1, 0, 0, fakeAuthor,
        Set.of(user.getId()), null);

    when(apiClient.post(eq("/api/posts/" + postId + "/likes"), eq(Collections.emptyMap()),
        eq(PostResponse.class))).thenReturn(expectedPost);

    PostResponse result = postService.likePost(postId);
    assertEquals(expectedPost, result);
  }

  @Test
  void postUpdateListenerNotification() {
    AtomicBoolean listenerCalled = new AtomicBoolean(false);
    postService.setPostUpdateListener(() -> listenerCalled.set(true));

    postService.notifyPostUpdated();
    assertTrue(listenerCalled.get());
  }
}
