package service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

import core.Post;
import core.User;
import core.payload.response.PostResponse;
import core.payload.response.UserResponse;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.reactive.function.client.WebClientResponseException;

// This JavaDoc comment was generated by Github Copilot
/**
 * Unit tests for PostService. Verifies retrieval and creation of posts with
 * mocks.
 */
@ExtendWith(MockitoExtension.class)
public class PostServiceTest {
  @Mock
  private ApiClientService apiClient;

  @InjectMocks
  private PostService postService;

  private User user;
  private Long postId;
  private Post post;

  @BeforeEach
  void setup() {
    this.user = new User(1L, "john", "John Pork", "pass");
    this.postId = 123L;
    this.post = new Post(this.user, "hello world", postId);
  }

  @Test
  void getPostByIdReturnsEmptyWhenNotFound() {
    WebClientResponseException exception = WebClientResponseException.create(404, "Not Found", null,
        null, null);
    when(apiClient.get(eq("/api/posts/" + postId), eq(PostResponse.class))).thenThrow(exception);
    assertTrue(postService.getPostById(postId).isEmpty());
  }

  @Test
  void getPostByIdReturnsPostWhenFound() {
    UserResponse fakeAuthor = new UserResponse(user.getId(), user.getUsername(),
        user.getDisplayName());
    PostResponse fakePost = new PostResponse(post.getId(), post.getContent(), post.getLikes(),
        post.getReTweets(), post.getCommentsAmount(), fakeAuthor, Set.of());
    when(apiClient.get(eq("/api/posts/" + postId), eq(PostResponse.class))).thenReturn(fakePost);
    assertEquals(fakePost, postService.getPostById(postId).get());
  }
}
