package service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

import core.User;
import core.payload.request.LoginRequest;
import core.payload.response.LoginResponse;
import core.payload.response.UserResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.reactive.function.client.WebClientResponseException;

// This JavaDoc comment was generated by Github Copilot
/**
 * Unit tests for UserService. Verifies retrieval and creation of users with
 * mocks.
 */
@ExtendWith(MockitoExtension.class)
public class UserServiceTest {
  @Mock
  private ApiClientService apiClient;

  @InjectMocks
  private UserService userService;

  private User user;

  @BeforeEach
  void setup() {
    this.user = new User(1L, "john", "John Pork", "pass");
  }

  @Test
  void logInReturnsTrueWhenUserExistsAndPasswordMatches() {
    LoginResponse fakeJwt = new LoginResponse("jwt-token");
    UserResponse fakeUser = new UserResponse(user.getId(), user.getUsername(),
        user.getDisplayName());

    when(apiClient.post(eq("/auth/login"), any(LoginRequest.class), eq(LoginResponse.class)))
        .thenReturn(fakeJwt);

    when(apiClient.get(eq("/auth/me"), eq(UserResponse.class))).thenReturn(fakeUser);

    assertTrue(userService.logIn(user.getUsername(), user.getPassword()));
    assertEquals(fakeUser, userService.getLoggedInUser());
  }

  @Test
  void logInReturnsFalseWhenUserExistsAndPasswordDoesNotMatch() {
    WebClientResponseException exception = WebClientResponseException.create(403, "Forbidden", null,
        null, null);
    when(apiClient.post(eq("/auth/login"), any(LoginRequest.class), eq(LoginResponse.class)))
        .thenThrow(exception);

    assertFalse(userService.logIn(user.getUsername(), user.getPassword()));
    assertNull(userService.getLoggedInUser());
  }
}
