package service;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.when;

import core.User;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import persistence.UserRepository;

// This JavaDoc comment was generated by Github Copilot
/**
 * Unit tests for UserService. Verifies retrieval and creation of users with
 * mocks.
 */
@ExtendWith(MockitoExtension.class)
public class UserServiceTest {
  @Mock
  private UserRepository userRepository;

  @InjectMocks
  private UserService userService;

  private User user;

  @BeforeEach
  void setup() {
    this.userService = new UserService();
    this.user = new User(1L, "john", "John Pork", "pass");
  }

  @Test
  void logInReturnsTrueWhenUserExistsAndPasswordMatches() {
    when(userRepository.findByUsername(user.getUsername())).thenReturn(Optional.of(user));
    boolean result = userService.logIn(user.getUsername(), user.getPassword());
    assertTrue(result);
    assertEquals(user, userService.getLoggedInUser());
  }

  @Test
  void logInReturnsFalseWhenUserExistsAndPasswordDoesNotMatch() {
    when(userRepository.findByUsername(user.getUsername())).thenReturn(Optional.of(user));
    boolean result = userService.logIn(user.getUsername(), "wrongpassword");
    assertFalse(result);
    assertNull(userService.getLoggedInUser());
  }

  @Test
  void logInCreatesNewUserWhenUserDoesNotExist() {
    when(userRepository.findByUsername("newuser")).thenReturn(Optional.empty());
    boolean result = userService.logIn("newuser", "newpassword");
    assertTrue(result);
    assertEquals(userService.getLoggedInUser().username(), "newuser");
  }
}
