package service;

import core.payload.request.CreatePostRequest;
import core.payload.response.PostResponse;
import java.util.List;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.reactive.function.client.WebClientResponseException;

// This JavaDoc comment was generated by Github Copilot
/**
 * Service for managing Post entities. Provides methods to retrieve and create
 * posts.
 */
@Service
public class PostService {
  @Autowired
  private ApiClientService apiClient;

  /**
   * Retrieves a post by its ID.
   *
   * @param id the Id of the post to retrieve.
   * @return an {@link Optional} containing the post if found, else empty.
   */
  @Transactional(readOnly = true)
  public Optional<PostResponse> getPostById(Long id) {
    PostResponse post;
    try {
      post = this.apiClient.get(
          "/api/posts/" + id,
          PostResponse.class);
    } catch (WebClientResponseException.NotFound e) {
      return Optional.empty();
    }

    return Optional.of(post);
  }

  // This JavaDoc comment was generated by Github Copilot
  /**
   * Creates a new post.
   *
   * @param post the post to create
   * @return the saved post
   */
  @Transactional
  public PostResponse createPost(String content) {
    if (content == null) {
      throw new IllegalArgumentException("Post cannot be null");
    }

    PostResponse post = this.apiClient.post(
        "/api/posts",
        new CreatePostRequest(content),
        PostResponse.class);

    return post;
  }

  @Transactional(readOnly = true)
  public List<PostResponse> getAllPosts() {
    return this.apiClient.get(
        "/api/posts",
        new ParameterizedTypeReference<List<PostResponse>>() {
        });
  }
}
