package service;

import core.payload.request.CreatePostRequest;
import core.payload.response.PostResponse;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import core.Post;
import core.User;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import org.springframework.web.reactive.function.client.WebClientResponseException;

// This JavaDoc comment was generated by Github Copilot
/**
 * Service for managing Post entities. Provides methods to retrieve and create
 * posts.
 */
@Service
public class PostService {
  @Autowired
  private ApiClientService apiClient;

  /**
   * Retrieves a post by its ID.
   *
   * @param id the Id of the post to retrieve.
   * @return an {@link Optional} containing the post if found, else empty.
   */
  @Transactional(readOnly = true)
  public Optional<PostResponse> getPostById(Long id) {
    PostResponse post;
    try {
      post = this.apiClient.get("/api/posts/" + id, PostResponse.class);
    } catch (WebClientResponseException.NotFound e) {
      return Optional.empty();
    }

    return Optional.of(post);
  }

  /**
   * Retrieves a post by its ID.
   *
   * @param id            the Id of the post to retrieve.
   * @param withRelations whether to fetch related entities (e.g. likes)
   * @return an {@link Optional} containing the post if found, else empty.
   */
  @Transactional(readOnly = true)
  public Optional<PostResponse> getPostById(Long id, boolean withRelations) {
    // TODO: implement this if needed
    throw new UnsupportedOperationException();
  }

  // This JavaDoc comment was generated by Github Copilot
  /**
   * Creates a new post.
   *
   * @param content the content of the post
   * @return the saved post
   */
  @Transactional
  public PostResponse createPost(String content) {
    if (content == null) {
      throw new IllegalArgumentException("Post cannot be null");
    }

    PostResponse post = this.apiClient.post("/api/posts", new CreatePostRequest(content),
        PostResponse.class);

    return post;
  }

  /** Returns a list of all posts. */
  @Transactional(readOnly = true)
  public List<PostResponse> getAllPosts() {
    return this.apiClient.get("/api/posts", new ParameterizedTypeReference<List<PostResponse>>() {
    });
  }

  /** Returns a list of all posts. */
  @Transactional(readOnly = true)
  public List<PostResponse> getAllPosts(boolean withRelations) {
    // TODO: implement this if needed
    throw new UnsupportedOperationException();
  }

  /** Returns a list of all posts by the @param user */
  @Transactional(readOnly = true)
  public List<Post> postsByUser(User user) {
    return this.postRepository.findPostsByUser(user);

    // return this.postRepository.findPostsByUser();
  }

  /** Likes/unlikes the @param post by the @param user . */
  @Transactional
  public PostResponse likePost(Long postId) {
    return this.apiClient.post("/api/posts/" + postId + "/likes", Collections.emptyMap(),
        PostResponse.class);
    notifyPostUpdated();
  }

  // TODO: add if needed
  // public PostResponse update(Post post) {
  // return postRepository.update(post);
  // }

  // FIXME: Do I need readonly?
  public int getPostCount(User user) {
    return this.postRepository.getPostCount(user);
  }

  public int getLikesCount(User user) {
    return this.postRepository.getLikesCount(user);
  }

  private Runnable postUpdateListener;

  public void setPostUpdateListener(Runnable listener) {
    this.postUpdateListener = listener;
  }

  public void notifyPostUpdated() {
    if (postUpdateListener != null) {
      postUpdateListener.run();
    }
  }

}
